# A short, descriptive name of this building block collection
name: Oceans Information Model

# Short abstract for this collection (optional)
abstract: |
  Defines a semantic model for interoperability between Components of Digital Twins of the Ocean or similar domain applications uisng a baseline of common standard models.

# Description for this collection (optional)
description: |
  TBD
  
# Customize the following prefix (will be prepended to the path of the building blocks):
identifier-prefix: ogc.model.oceans.


# List of imports ("default" is an alias for the main OGC Building Blocks Register)
imports:
  - default
  - https://ogcincubator.github.io/cross-domain-model/build/register.json

# SPARQL configuration (optional)
#   Authentication can be set through the sparql_username and sparql_password GitHub Workflow inputs
#   (see .github/workflow/process-bblocks.yml)
#
# sparql:
#   push: https://example.com/gsp           # SPARQL Graph Store Protocol endpoint for uploading data
#   graph: https://my.bblocks.example.com/  # SPARQL Graph where data will be uploaded
#                                           #  if left empty, the base URL for the publication will be used
#   query: https://example.com/sparql       # SPARQL query endpoint where data will be available
